# This is a basic workflow to help you get started with Actions

name: triggered by other workflow - develop

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["CI"]
    branches:
      - develop
      - 'ft/**'
    types: 
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  echo2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
