name: triggered by other workflow - main

on:
  workflow_run:
    workflows: ["CI"]
    branches:
      - main
    types: 
      - completed
  workflow_call:
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  echo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo ${GITHUB_REF}
          echo ${GITHUB_HEAD_REF}
          echo ${GITHUB_BASE_REF}
          
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          github_token: ${{ secrets._GITHUB_TOKEN }}
          pr_allow_empty: true
          
