name: PR Labeler

on:
  pull_request:
    types: [opened]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest

    steps:
      - name: env
        run: |
          export

      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml # optional, .github/pr-labeler.yml is the default value
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  auto-udpate:
    runs-on: ubuntu-latest

    steps:
      - name: wait
        run: sleep 10

      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          DRY_RUN: "false"
          PR_FILTER: "protected"
          RETRY_COUNT: "5"
          RETRY_SLEEP: "300"
          MERGE_CONFLICT_ACTION: "fail"

#  labeler:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/labeler@v3
#        with:
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          configuration-path: .github/labeler.yml