name: CI-sync

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    
jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: Push changes master to develop
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: pull-request
        uses: repo-sync/pull-request@v2
        if: ${{ failure() }}        
        with:
          destination_branch: main
          pr_reviewer: "$GITHUB_ACTOR"
          pr_assignee: "$GITHUB_ACTOR"
          github_token: ${{ secrets.GITHUB_TOKEN }}
