name: CI-sync

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    
jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: env
        run: |
          export

      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: main

      - name: env
        run: |
          export

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

#      - name: Bump version and push tag
#        id: tag_version
#        uses: mathieudutour/github-tag-action@v6.0
#        with:
#          release_branches: main,develop
#          github_token: ${{ secrets._GITHUB_TOKEN }}

      # - name: Create a new tag
      #   uses: actions-ecosystem/action-push-tag@v1
      #   with:
      #     tag: ${{ steps.tag_version.outputs.new_tag }}
      #     message: Release ${{ steps.tag_version.outputs.new_tag }}
          
      # - name: Create a GitHub release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     tag: ${{ steps.tag_version.outputs.new_tag }}
      #     name: Release ${{ steps.tag_version.outputs.new_tag }} 
      #     body: ${{ steps.tag_version.outputs.changelog }}

  create-pr:
    needs: [ tagging ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: develop

      - name: Generate PR master to develop
        id: cpr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: main
          pr_reviewer: "$GITHUB_ACTOR"
          pr_assignee: "$GITHUB_ACTOR"
          pr_title: "Develop to Master"
          pr_label: "auto-pr"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: output-number
        run: echo ${{steps.cpr.outputs.pr_number}}

  merge:
    needs: [ create-pr ]
    runs-on: ubuntu-18.04

    steps:
      - name: wait
        run: sleep 10

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pr_number != 0
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          pull-request-number: ${{ steps.cpr.outputs.pr_number }}
          merge-method: merge
          token: ${{ secrets.GITHUB_TOKEN }}
