name: CI

on:
  push:
    branches:
      - main
      - master
      - develop
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Run a one-line script
  #       run: echo Hello, world!

  #     - name: env
  #       run : |
  #         export
  #         sleep 100

  #     - name: run on tags
  #       if: ${{ github.ref_type	 == 'tag'}}
  #       run: |
  #         echo "이곳은 태그"
          
  #     - name: run on master
  #       if: ${{ github.ref == 'refs/heads/master' }}
  #       run: |
  #         echo "이곳은 마스터22"
  #         export MOSHI_VAR=test

  #     - name: Define variables
  #       run: echo "${TAG_TEST}"
  #       env:
  #         TAG_TEST: $(cat Dockerfile | grep APP_NAME= | head -n 1 | grep -o '".*"' | sed 's/"//g')
  publish:
    runs-on: ubuntu-latest
    outputs:
      server-gitlog: ${{ steps.commit-msg.outputs.GITLOG }}

    steps:
      - uses: actions/checkout@v3

      - name: Set env
        id: commit-msg
        run: |
          echo "::set-output name=GITLOG::$(git log -1 --no-merges --pretty=format:"%s | %h")"          

  modify_manifest:
    needs: [ publish ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
          token: ${{ secrets._GITHUB_TOKEN }}

      - name: Set develop environment tag
        run: |
          echo $GITHUB_SHA > $GITHUB_SHA
          
      - name: Commit kustomization
        run: |
          git config --local user.email "drpalette-bot@medibloc.org"
          git config --local user.name "drpalette-bot"
          git commit -a -m "SVR-MSG::${{needs.publish.outputs.server-gitlog}}"

      - name: Push changes to master
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          repository: medibloc/drpalette-infra
          branch: master
          force: true
