name: CI

on:
  push:
    branches:
      - main
      - master
      - develop
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: env
        run : |
          export        

      - name: run on tags
        if: ${{ github.ref_type	 == 'tag'}}
        run: |
          echo "이곳은 태그"
          
      - name: run on master
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          echo "이곳은 마스터22"
          export MOSHI_VAR=test

      - name: run on develop
        if: ${{ github.base_ref == 'develop'}}
        run: |
          echo "이곳은 디벨롭"
          sleep 100

      - name: Define variables
        run: echo "${TAG_TEST}"
        env:
          TAG_TEST: $(cat Dockerfile | grep APP_NAME= | head -n 1 | grep -o '".*"' | sed 's/"//g')
